/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kelimeoyunu;

/**
 *
 * @author Yakup
 */
public class AnaMenu extends javax.swing.JFrame {

    /**
     * Creates new form AnaMenu
     */
    public AnaMenu() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        anaMenuPanel = new javax.swing.JPanel();
        oyunaBaşlaButton = new javax.swing.JButton();
        kelimeEkleAnaEkranButton = new javax.swing.JButton();
        kelimeOyunu = new javax.swing.JLabel();
        kelimeDüzenleSilButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ana Menü");
        setAutoRequestFocus(false);
        setBackground(java.awt.SystemColor.control);
        setName("AnaMenu"); // NOI18N
        setResizable(false);

        anaMenuPanel.setBackground(new java.awt.Color(0, 180, 180));
        anaMenuPanel.setName("anaMenuPanel"); // NOI18N

        oyunaBaşlaButton.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        oyunaBaşlaButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kelimeoyunu/Project Icons Resized/oyunaBaşla.png"))); // NOI18N
        oyunaBaşlaButton.setText("Oyuna Başla");
        oyunaBaşlaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oyunaBaşlaButtonActionPerformed(evt);
            }
        });

        kelimeEkleAnaEkranButton.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        kelimeEkleAnaEkranButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kelimeoyunu/Project Icons Resized/kelimeEkle.png"))); // NOI18N
        kelimeEkleAnaEkranButton.setText("Kelime Ekle");
        kelimeEkleAnaEkranButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kelimeEkleAnaEkranButtonActionPerformed(evt);
            }
        });

        kelimeOyunu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kelimeoyunu/Project Icons Resized/download.png"))); // NOI18N

        kelimeDüzenleSilButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        kelimeDüzenleSilButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kelimeoyunu/Project Icons Resized/düzenle.png"))); // NOI18N
        kelimeDüzenleSilButton.setText("Kelime Düzenle veya Sil");
        kelimeDüzenleSilButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kelimeDüzenleSilButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout anaMenuPanelLayout = new javax.swing.GroupLayout(anaMenuPanel);
        anaMenuPanel.setLayout(anaMenuPanelLayout);
        anaMenuPanelLayout.setHorizontalGroup(
            anaMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(anaMenuPanelLayout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addGroup(anaMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kelimeDüzenleSilButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(oyunaBaşlaButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kelimeEkleAnaEkranButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(210, 210, 210))
            .addGroup(anaMenuPanelLayout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(kelimeOyunu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        anaMenuPanelLayout.setVerticalGroup(
            anaMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(anaMenuPanelLayout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addComponent(kelimeOyunu, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(oyunaBaşlaButton)
                .addGap(9, 9, 9)
                .addComponent(kelimeEkleAnaEkranButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kelimeDüzenleSilButton)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(anaMenuPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 686, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(anaMenuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        anaMenuPanel.getAccessibleContext().setAccessibleName("AnaMenu");

        getAccessibleContext().setAccessibleName("AnaMenu");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kelimeEkleAnaEkranButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kelimeEkleAnaEkranButtonActionPerformed
        // TODO add your handling code here:
        new KelimeEkle().setVisible(true);
    }//GEN-LAST:event_kelimeEkleAnaEkranButtonActionPerformed

    private void oyunaBaşlaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oyunaBaşlaButtonActionPerformed
        // TODO add your handling code here:
        new OyunEkranı().setVisible(true);
    }//GEN-LAST:event_oyunaBaşlaButtonActionPerformed

    private void kelimeDüzenleSilButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kelimeDüzenleSilButtonActionPerformed
        // TODO add your handling code here:
        new KelimeDüzenleSil().setVisible(true);
    }//GEN-LAST:event_kelimeDüzenleSilButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnaMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel anaMenuPanel;
    private javax.swing.JButton kelimeDüzenleSilButton;
    private javax.swing.JButton kelimeEkleAnaEkranButton;
    private javax.swing.JLabel kelimeOyunu;
    private javax.swing.JButton oyunaBaşlaButton;
    // End of variables declaration//GEN-END:variables
}
