/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kelimeoyunu;

import javax.swing.*;
import java.util.*;
import java.io.*;

/**
 *
 * @author Yakup
 */
public class KelimeEkle extends javax.swing.JFrame {

    ArrayList<Soru> sorular;

    /**
     * Creates new form KelimeEkle
     */
    public KelimeEkle() {
        initComponents();
        sorular = new ArrayList<Soru>();
        arrayListiDoldur();

        kelimeninTanımıTextArea.setLineWrap(true);
        kelimeninTanımıTextArea.setWrapStyleWord(true);

    }

    public void arrayListiDoldur() {
        try {
            FileInputStream file = new FileInputStream("Sorular.txt");
            ObjectInput inputFile = new ObjectInputStream(file);

            boolean dosyaSonu = false;
            while (!dosyaSonu) {
                try {
                    sorular.add((Soru) inputFile.readObject());
                } catch (EOFException e) {
                    dosyaSonu = true;
                } catch (Exception f) {
                    JOptionPane.showMessageDialog(null, f.getMessage());
                }
            }
            inputFile.close();
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    public void soruyuDosyayaKaydet() {
        try {
            FileOutputStream file = new FileOutputStream("Sorular.txt");
            ObjectOutputStream outputFile = new ObjectOutputStream(file);

            for (int i = 0; i < sorular.size(); i++) {
                outputFile.writeObject(sorular.get(i));
            }
            outputFile.close();
            JOptionPane.showMessageDialog(null, "Kelime tanımı ve kelime başarıyla eklendi.");

        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kelimeEklePanel = new javax.swing.JPanel();
        kelimeTanımıLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Uyarı = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        kelimeninTanımıTextArea = new javax.swing.JTextArea();
        kelimeLabel = new javax.swing.JLabel();
        kelimeTextField = new javax.swing.JTextField();
        kelimeEklemeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Kelime Ekle");
        setResizable(false);

        kelimeEklePanel.setBackground(new java.awt.Color(0, 180, 180));
        kelimeEklePanel.setName("kelimeEklePanel"); // NOI18N

        kelimeTanımıLabel.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        kelimeTanımıLabel.setText("Kelimenin Tanımı");

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        Uyarı.setEditable(false);
        Uyarı.setBackground(new java.awt.Color(204, 204, 204));
        Uyarı.setColumns(20);
        Uyarı.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        Uyarı.setForeground(new java.awt.Color(255, 0, 0));
        Uyarı.setRows(5);
        Uyarı.setText("UYARI\nEkleyeceğiniz kelimenin en az dört , en fazla \non harfli olması gerekmektedir.");
        jScrollPane1.setViewportView(Uyarı);

        kelimeninTanımıTextArea.setBackground(new java.awt.Color(255, 255, 255));
        kelimeninTanımıTextArea.setColumns(20);
        kelimeninTanımıTextArea.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        kelimeninTanımıTextArea.setRows(5);
        jScrollPane2.setViewportView(kelimeninTanımıTextArea);

        kelimeLabel.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        kelimeLabel.setText("Kelime");

        kelimeTextField.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N

        kelimeEklemeButton.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        kelimeEklemeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kelimeoyunu/Project Icons Resized/kelimeEkle.png"))); // NOI18N
        kelimeEklemeButton.setText("Kelime Ekle");
        kelimeEklemeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kelimeEklemeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kelimeEklePanelLayout = new javax.swing.GroupLayout(kelimeEklePanel);
        kelimeEklePanel.setLayout(kelimeEklePanelLayout);
        kelimeEklePanelLayout.setHorizontalGroup(
            kelimeEklePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kelimeEklePanelLayout.createSequentialGroup()
                .addGroup(kelimeEklePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kelimeEklePanelLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(kelimeEklePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(kelimeLabel)
                            .addComponent(jScrollPane2)
                            .addComponent(kelimeTextField)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 526, Short.MAX_VALUE)
                            .addComponent(kelimeTanımıLabel)))
                    .addGroup(kelimeEklePanelLayout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(kelimeEklemeButton)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        kelimeEklePanelLayout.setVerticalGroup(
            kelimeEklePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kelimeEklePanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(kelimeTanımıLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kelimeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kelimeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(kelimeEklemeButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kelimeEklePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kelimeEklePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        kelimeEklePanel.getAccessibleContext().setAccessibleName("KelimeEkle");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kelimeEklemeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kelimeEklemeButtonActionPerformed
        // TODO add your handling code here:

        if (kelimeninTanımıTextArea.getText().isEmpty() || kelimeTextField.getText().trim().length() < 4 || kelimeTextField.getText().trim().length() > 10) {
            JOptionPane.showMessageDialog(null, "Lütfen alanları düzgün bir şekilde doldurunuz.");
        } else {
            String tanım = kelimeninTanımıTextArea.getText().trim();
            String kelime = kelimeTextField.getText().trim().toUpperCase();

            Soru soru = new Soru(tanım, kelime);

            sorular.add(soru);

            soruyuDosyayaKaydet();

            kelimeninTanımıTextArea.setText("");
            kelimeTextField.setText("");

        }

    }//GEN-LAST:event_kelimeEklemeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KelimeEkle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KelimeEkle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KelimeEkle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KelimeEkle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KelimeEkle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Uyarı;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel kelimeEklePanel;
    private javax.swing.JButton kelimeEklemeButton;
    private javax.swing.JLabel kelimeLabel;
    private javax.swing.JLabel kelimeTanımıLabel;
    private javax.swing.JTextField kelimeTextField;
    private javax.swing.JTextArea kelimeninTanımıTextArea;
    // End of variables declaration//GEN-END:variables
}
