/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kelimeoyunu;

import javax.swing.*;
import java.util.*;
import java.io.*;

/**
 *
 * @author Yakup
 */
public class KelimeDüzenleSil extends javax.swing.JFrame {

    ArrayList<Soru> sorular;
    String[] kelimelerDizi;

    /**
     * Creates new form KelimeDüzenleSil
     */
    public KelimeDüzenleSil() {
        initComponents();

        kelimeninTanımıTextArea.setLineWrap(true);
        kelimeninTanımıTextArea.setWrapStyleWord(true);

        sorular = new ArrayList<Soru>();
        arrayListiDoldur();

        kelimelerDizi = new String[sorular.size()];

        for (int i = 0; i < sorular.size(); i++) {
            kelimelerDizi[i] = sorular.get(i).kelime;
        }
        kelimeSeçComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(kelimelerDizi));

        kelimeSeçComboBox.setSelectedIndex(0);
    }

    public void arrayListiDoldur() {
        try {
            FileInputStream file = new FileInputStream("Sorular.txt");
            ObjectInput inputFile = new ObjectInputStream(file);

            boolean dosyaSonu = false;
            while (!dosyaSonu) {
                try {
                    sorular.add((Soru) inputFile.readObject());
                } catch (EOFException e) {
                    dosyaSonu = true;
                } catch (Exception f) {
                    JOptionPane.showMessageDialog(null, f.getMessage());
                }
            }
            inputFile.close();
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    public void soruyuDosyayaKaydet() {
        try {
            FileOutputStream file = new FileOutputStream("Sorular.txt");
            ObjectOutputStream outputFile = new ObjectOutputStream(file);

            for (int i = 0; i < sorular.size(); i++) {
                outputFile.writeObject(sorular.get(i));
            }
            outputFile.close();

        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kelimeDüzenleSil = new javax.swing.JPanel();
        kelimeSeçLabel = new javax.swing.JLabel();
        kelimeSeçComboBox = new javax.swing.JComboBox<>();
        kelimeTanımıLabel = new javax.swing.JLabel();
        kelimeLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        kelimeninTanımıTextArea = new javax.swing.JTextArea();
        kelimeTextField = new javax.swing.JTextField();
        düzenleButton = new javax.swing.JButton();
        silButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Kelime Düzenle veya Sil");
        setResizable(false);

        kelimeDüzenleSil.setBackground(new java.awt.Color(0, 180, 180));

        kelimeSeçLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        kelimeSeçLabel.setText("Kelime Seç:");

        kelimeSeçComboBox.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        kelimeSeçComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        kelimeSeçComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kelimeSeçComboBoxActionPerformed(evt);
            }
        });

        kelimeTanımıLabel.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        kelimeTanımıLabel.setText("Kelimenin Tanımı");

        kelimeLabel.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        kelimeLabel.setText("Kelime");

        kelimeninTanımıTextArea.setBackground(new java.awt.Color(255, 255, 255));
        kelimeninTanımıTextArea.setColumns(20);
        kelimeninTanımıTextArea.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        kelimeninTanımıTextArea.setRows(5);
        jScrollPane2.setViewportView(kelimeninTanımıTextArea);

        kelimeTextField.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N

        düzenleButton.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        düzenleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kelimeoyunu/Project Icons Resized/düzenle.png"))); // NOI18N
        düzenleButton.setText("Düzenle");
        düzenleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                düzenleButtonActionPerformed(evt);
            }
        });

        silButton.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        silButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kelimeoyunu/Project Icons Resized/sil.png"))); // NOI18N
        silButton.setText("Sil");
        silButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                silButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kelimeDüzenleSilLayout = new javax.swing.GroupLayout(kelimeDüzenleSil);
        kelimeDüzenleSil.setLayout(kelimeDüzenleSilLayout);
        kelimeDüzenleSilLayout.setHorizontalGroup(
            kelimeDüzenleSilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kelimeDüzenleSilLayout.createSequentialGroup()
                .addGroup(kelimeDüzenleSilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kelimeDüzenleSilLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(kelimeDüzenleSilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(kelimeLabel)
                            .addGroup(kelimeDüzenleSilLayout.createSequentialGroup()
                                .addComponent(kelimeSeçLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(kelimeSeçComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(kelimeTanımıLabel)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE)
                            .addComponent(kelimeTextField)))
                    .addGroup(kelimeDüzenleSilLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(düzenleButton)
                        .addGap(33, 33, 33)
                        .addComponent(silButton, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        kelimeDüzenleSilLayout.setVerticalGroup(
            kelimeDüzenleSilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kelimeDüzenleSilLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(kelimeDüzenleSilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kelimeSeçLabel)
                    .addComponent(kelimeSeçComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(kelimeTanımıLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(kelimeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(kelimeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(kelimeDüzenleSilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(düzenleButton)
                    .addComponent(silButton))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kelimeDüzenleSil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kelimeDüzenleSil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void düzenleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_düzenleButtonActionPerformed
        // TODO add your handling code here:
        if (kelimeninTanımıTextArea.getText().isEmpty() || kelimeTextField.getText().trim().length() < 4 || kelimeTextField.getText().trim().length() > 10) {
            JOptionPane.showMessageDialog(null, "Lütfen alanları düzgün bir şekilde doldurunuz.");
        } else {
            int seçilenIndex = kelimeSeçComboBox.getSelectedIndex();

            sorular.get(seçilenIndex).tanım = kelimeninTanımıTextArea.getText();
            sorular.get(seçilenIndex).kelime = kelimeTextField.getText().trim().toUpperCase();

            soruyuDosyayaKaydet();
            
            kelimelerDizi = new String[sorular.size()];
            
            for (int i = 0; i < sorular.size(); i++) {
                kelimelerDizi[i] = sorular.get(i).kelime;
            }
            kelimeSeçComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(kelimelerDizi));

            kelimeSeçComboBox.setSelectedIndex(0);

            JOptionPane.showMessageDialog(null, "Kelime tanımı ve kelime başarıyla düzenlendi.");

        }

    }//GEN-LAST:event_düzenleButtonActionPerformed

    private void silButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_silButtonActionPerformed
        // TODO add your handling code here:
        int seçilenIndex = kelimeSeçComboBox.getSelectedIndex();

        sorular.remove(seçilenIndex);

        soruyuDosyayaKaydet();
        
        kelimelerDizi = new String[sorular.size()];

        for (int i = 0; i < sorular.size(); i++) {
            kelimelerDizi[i] = sorular.get(i).kelime;
        }
        kelimeSeçComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(kelimelerDizi));

        kelimeSeçComboBox.setSelectedIndex(0);

        JOptionPane.showMessageDialog(null, "Kelime tanımı ve kelime başarıyla silindi.");
    }//GEN-LAST:event_silButtonActionPerformed

    private void kelimeSeçComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kelimeSeçComboBoxActionPerformed
        // TODO add your handling code here:
        int seçilenIndex = kelimeSeçComboBox.getSelectedIndex();

        kelimeninTanımıTextArea.setText(sorular.get(seçilenIndex).tanım);
        kelimeTextField.setText(sorular.get(seçilenIndex).kelime);
    }//GEN-LAST:event_kelimeSeçComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KelimeDüzenleSil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KelimeDüzenleSil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KelimeDüzenleSil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KelimeDüzenleSil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KelimeDüzenleSil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton düzenleButton;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel kelimeDüzenleSil;
    private javax.swing.JLabel kelimeLabel;
    private javax.swing.JComboBox<String> kelimeSeçComboBox;
    private javax.swing.JLabel kelimeSeçLabel;
    private javax.swing.JLabel kelimeTanımıLabel;
    private javax.swing.JTextField kelimeTextField;
    private javax.swing.JTextArea kelimeninTanımıTextArea;
    private javax.swing.JButton silButton;
    // End of variables declaration//GEN-END:variables
}
