/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kelimeoyunu;

import java.io.EOFException;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.time.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Yakup
 */
public class OyunBitiş extends javax.swing.JFrame {

    ArrayList<Oyuncu> oyuncular;

    /**
     * Creates new form OyunBitiş
     */
    public OyunBitiş() {
        initComponents();
    }

    public OyunBitiş(String oyuncuAdı, int puan, int kalanSüre, String tarih, String zaman) {
        initComponents();
        oyuncuAdıOyunBittiTextField.setText(oyuncuAdı);
        puanOyunBittiTextField.setText(String.valueOf(puan));
        kalanSüreOyunBittiTextField.setText(String.valueOf(kalanSüre));
        tarihOyunBittiTextField.setText(tarih);
        zamanOyunBittiTextField.setText(zaman);

        oyuncular = new ArrayList<Oyuncu>();

        arrayListiDoldur();

        Oyuncu oyuncu = new Oyuncu(oyuncuAdı, puan, kalanSüre, tarih, zaman);

        oyuncular.add(oyuncu);

        oyuncuyuDosyayaKaydet();
    }

    public void arrayListiDoldur() {
        try {
            FileInputStream file = new FileInputStream("Oyuncular.txt");
            ObjectInput inputFile = new ObjectInputStream(file);

            boolean dosyaSonu = false;
            while (!dosyaSonu) {
                try {
                    oyuncular.add((Oyuncu) inputFile.readObject());
                } catch (EOFException e) {
                    dosyaSonu = true;
                } catch (Exception f) {
                    JOptionPane.showMessageDialog(null, f.getMessage());
                }
            }
            inputFile.close();
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    public void oyuncuyuDosyayaKaydet() {
        try {
            FileOutputStream file = new FileOutputStream("Oyuncular.txt");
            ObjectOutputStream outputFile = new ObjectOutputStream(file);

            for (int i = 0; i < oyuncular.size(); i++) {
                outputFile.writeObject(oyuncular.get(i));
            }
            outputFile.close();
            JOptionPane.showMessageDialog(null, "Oyuncu ve bilgileri metin dosyasına eklendi.");

        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        oyunBittiPanel = new javax.swing.JPanel();
        oyunBittiLabel = new javax.swing.JLabel();
        oyuncuAdıOyunBittiLabel = new javax.swing.JLabel();
        oyuncuAdıOyunBittiTextField = new javax.swing.JTextField();
        kalanSüreOyunBittiLabel = new javax.swing.JLabel();
        tarihOyunBittiLabel = new javax.swing.JLabel();
        puanOyunBittiLabel = new javax.swing.JLabel();
        zamanOyunBittiLabel = new javax.swing.JLabel();
        puanOyunBittiTextField = new javax.swing.JTextField();
        kalanSüreOyunBittiTextField = new javax.swing.JTextField();
        tarihOyunBittiTextField = new javax.swing.JTextField();
        zamanOyunBittiTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Oyun Bitti");
        setResizable(false);

        oyunBittiPanel.setBackground(new java.awt.Color(0, 180, 180));

        oyunBittiLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kelimeoyunu/Project Icons Resized/oyunBitti.png"))); // NOI18N

        oyuncuAdıOyunBittiLabel.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        oyuncuAdıOyunBittiLabel.setText("Oyuncu Adı:");

        oyuncuAdıOyunBittiTextField.setEditable(false);
        oyuncuAdıOyunBittiTextField.setBackground(new java.awt.Color(200, 200, 200));
        oyuncuAdıOyunBittiTextField.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N

        kalanSüreOyunBittiLabel.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        kalanSüreOyunBittiLabel.setText("Kalan Süre(sn):");

        tarihOyunBittiLabel.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        tarihOyunBittiLabel.setText("Tarih:");

        puanOyunBittiLabel.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        puanOyunBittiLabel.setText("Puanı:");

        zamanOyunBittiLabel.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        zamanOyunBittiLabel.setText("Zaman:");

        puanOyunBittiTextField.setEditable(false);
        puanOyunBittiTextField.setBackground(new java.awt.Color(200, 200, 200));
        puanOyunBittiTextField.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        puanOyunBittiTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puanOyunBittiTextFieldActionPerformed(evt);
            }
        });

        kalanSüreOyunBittiTextField.setEditable(false);
        kalanSüreOyunBittiTextField.setBackground(new java.awt.Color(200, 200, 200));
        kalanSüreOyunBittiTextField.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N

        tarihOyunBittiTextField.setEditable(false);
        tarihOyunBittiTextField.setBackground(new java.awt.Color(200, 200, 200));
        tarihOyunBittiTextField.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N

        zamanOyunBittiTextField.setEditable(false);
        zamanOyunBittiTextField.setBackground(new java.awt.Color(200, 200, 200));
        zamanOyunBittiTextField.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N

        javax.swing.GroupLayout oyunBittiPanelLayout = new javax.swing.GroupLayout(oyunBittiPanel);
        oyunBittiPanel.setLayout(oyunBittiPanelLayout);
        oyunBittiPanelLayout.setHorizontalGroup(
            oyunBittiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(oyunBittiPanelLayout.createSequentialGroup()
                .addGroup(oyunBittiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(oyunBittiPanelLayout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addGroup(oyunBittiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kalanSüreOyunBittiLabel)
                            .addComponent(tarihOyunBittiLabel)
                            .addComponent(zamanOyunBittiLabel)
                            .addComponent(puanOyunBittiLabel)
                            .addComponent(oyuncuAdıOyunBittiLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(oyunBittiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(oyuncuAdıOyunBittiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(oyunBittiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(puanOyunBittiTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                                .addComponent(kalanSüreOyunBittiTextField)
                                .addComponent(tarihOyunBittiTextField)
                                .addComponent(zamanOyunBittiTextField))))
                    .addGroup(oyunBittiPanelLayout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(oyunBittiLabel)))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        oyunBittiPanelLayout.setVerticalGroup(
            oyunBittiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(oyunBittiPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(oyunBittiLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(oyunBittiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oyuncuAdıOyunBittiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(oyuncuAdıOyunBittiLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(oyunBittiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(puanOyunBittiLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                    .addComponent(puanOyunBittiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(oyunBittiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kalanSüreOyunBittiLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                    .addComponent(kalanSüreOyunBittiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(oyunBittiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tarihOyunBittiLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                    .addComponent(tarihOyunBittiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(oyunBittiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(zamanOyunBittiLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zamanOyunBittiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(oyunBittiPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(oyunBittiPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void puanOyunBittiTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puanOyunBittiTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_puanOyunBittiTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OyunBitiş.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OyunBitiş.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OyunBitiş.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OyunBitiş.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OyunBitiş().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel kalanSüreOyunBittiLabel;
    private javax.swing.JTextField kalanSüreOyunBittiTextField;
    private javax.swing.JLabel oyunBittiLabel;
    private javax.swing.JPanel oyunBittiPanel;
    private javax.swing.JLabel oyuncuAdıOyunBittiLabel;
    private javax.swing.JTextField oyuncuAdıOyunBittiTextField;
    private javax.swing.JLabel puanOyunBittiLabel;
    private javax.swing.JTextField puanOyunBittiTextField;
    private javax.swing.JLabel tarihOyunBittiLabel;
    private javax.swing.JTextField tarihOyunBittiTextField;
    private javax.swing.JLabel zamanOyunBittiLabel;
    private javax.swing.JTextField zamanOyunBittiTextField;
    // End of variables declaration//GEN-END:variables
}
